//
//  NewsfeedModels.swift
//  News
//
//  Created by Macbook on 9/6/19.
//  Copyright (c) 2019 iMac GWS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Newsfeed
{
  // MARK: Use cases
  
  enum Model
  {
    struct Request
    {
        enum RequestType
        {
            case getNewsfeed
            case getUser
            case revealPostIds(postId: Int)
            case getNextBatch
        }
    }
    struct Response
    {
        enum ResponseType
        {
            case presentNewsFeed(feed: FeedResponse, revealedPostIds: [Int])
            case presentUserInfo(user: UserResponse?)
            case presentFooterLoader
        }
    }
    struct ViewModel
    {
        enum viewModelData
        {
            case displayNewsFeed(feedViewModel: FeedViewModel)
            case displayUser(userViewModel: UserViewModel)
            case displayFooterLoader
        }
    }
  }
}

struct UserViewModel: TitleViewViewModel {
    var photoUrlString: String?
}

struct FeedViewModel {
    struct Cell: FeedCellViewModel {
        var postId: Int
        var iconUrlStirng: String
        var name: String
        var date: String
        var text: String
        var likes: String
        var commits: String
        var shares: String
        var views: String
        var photoAttachments: [FeedCellPhotoAttachmentViewModel]
        var feedCellSizes: FeedCellSizes
    }
    
    struct FeedCellPhotoAttachment: FeedCellPhotoAttachmentViewModel {
        
        var photoUrlString: String? 
        var width: Int
        var height: Int
    }
    
    let cells: [Cell]
    let footerTitle: String? 
}
