//
//  NewsfeedModels.swift
//  News
//
//  Created by Macbook on 9/6/19.
//  Copyright (c) 2019 iMac GWS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Newsfeed
{
  // MARK: Use cases
  
  enum Model
  {
    struct Request
    {
        enum RequestType
        {
            case getNewsfeed
        }
    }
    struct Response
    {
        enum ResponseType
        {
            case presentNewsFeed(feed: FeedResponse)
        }
    }
    struct ViewModel
    {
        enum viewModelData
        {
            case displayNewsFeed(feedViewModel: FeedViewModel)
        }
    }
  }
}

struct FeedViewModel {
    struct Cell: FeedCellViewModel {
        var iconUrlStirng: String
        var name: String
        var date: String
        var text: String
        var likes: String
        var commits: String
        var shares: String
        var views: String
        var photoAttachment: FeedCellPhotoAttachmentViewModel?
        var feedCellSizes: FeedCellSizes
    }
    
    struct FeedCellPhotoAttachment: FeedCellPhotoAttachmentViewModel {
        
        var photoUrlString: String? 
        var width: Int
        var height: Int
    }
    
    let cells: [Cell]
}
